name: Delete Docker Image on Branch Deletion

# on:
#   delete:
#     branches:
#       - '**'
on:
  push:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  delete-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name : Get the version id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /user/packages/container/ark/versions
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Extract Version ID
        run: |
          VERSION_ID=$(echo "$RESPONSE" | jq '.[] | select(.metadata.container.tags[] == "upgrade-1") | .id')
          echo "VERSION_ID=$VERSION_ID" >> "$GITHUB_ENV"
      - name: Delete container
        run: |
          echo $VERSION_ID
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /users/${{ github.actor }}/packages/container/ark/versions/$VERSION_ID
